#!/bin/bash
cd LLaMA-Factory
CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage sft \
    --do_train True \
    --model_name_or_path unsloth/llama-3-8b-Instruct-bnb-4bit \
    --use_unsloth true \
    --template llama3 \
    --dataset_dir data \
    --dataset zh_tw_reading_comprehension,alpaca_gpt4_zh \
    --finetuning_type lora \
    --lora_target all \
    --lora_rank 16 \
    --loraplus_lr_ratio 16.0 \
    --quantization_bit 4 \
    --upcast_layernorm True \
    --cutoff_len 1024 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 3 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 10 \
    --save_steps 100 \
    --warmup_ratio 0.1 \
    --optim adamw_torch \
    --output_dir saves/LLaMA3-8B/sft4 \
    --overwrite_output_dir \
    --plot_loss \
    --fp16 True
